.TH HAILLO 1 "FEBRUARY 2025" Linux "User Manuals"
.SH NAME
Haillo \- a pseudo-terminal multiplexer for hai (hcli_hai), the HCLI command line AI chat and agent application.
.SH SYNOPSIS
.B haillo
[ option | <command> ]
.SH DESCRIPTION
.B haillo
is a python pseudo-terminal multiplexer (pty mux) and terminal UI for hai (hcli_hai), the HCLI command line AI chat and agent application.
.sp
The pty mux can be invoked via python package name (simply typing haillo in the terminal after installing haillo via pip). The script is tied into python package version dependencies to help maintain semantic expectations, notably against huckle and hcli_hai.
.sp
Note that huckle must be setup to interact with the hcli_hai backend for haillo to be able to make use of hai (e.g. huckle cli install localhost:10000 (e.g. where hcli_hai could be running on hcli_core)).
.sp
Also note that in addition to its python huckle and hcli_hai dependencies, haillo is dependent on a small amount of bash scripting, fzf (fuzzy finder) and gum (pretty output).
.sp
Haillo's agent automation attempt to execute local bash commands as proposed by the hai agent orchestrator. A whitelist helps provide some measure of protection on destructive activities.
.SH COMMANDS
.IP help
This help file.
.SH OPTIONS
.IP --version
.B haillo
version and the version of it's dependencies.
.SH LEADER KEYS
ctrl+space - global enablement
.sp
,m - model selection with fzf fuzzy search.
.br
,p - provider selection with fzf fuzzy search.
.br
,c - conversation selection with fzf fuzzy search.
.br
,r - conversation reset with gum confirmation.
.br
,v - voice assistant toggling
.br
,a - agent assistant toggling
.br
,s - show the latest complete conversation context
.br
,t - auto title re-generation for the current conversation
.br
,i - incremental agent plan step walk with gum status output
.br
,g - automated agent plan step walk to completion with gum status output
.br
,w - wrap a line of text written to the terminal and fed to history in an echo command and send it to hai --async
.SH EXAMPLE
haillo
.sp
haillo help
.sp
haillo --version
